Repository jzaragosa06/ats-backend, pull requests merged in 2025-04, with the labels that each got.

#38 fix:add or update existing smtp
  src/models/userConfiguration/smtpModel.js
Labels: enhancement

#45 feat: enhance application trend query to include year and month number
  src/controllers/analytic/graphsController.js
Labels: enhancement

#50 Refactor model controller
  src/controllers/applicant/addApplicantController.js
  src/controllers/applicant/applicantController.js
  src/controllers/email/emailController.js
  src/models/applicant/applicantModel.js
  src/models/user/userModel.js
Labels: Fix, refactor

#61 Fix email sig
  src/controllers/email/emailController.js
  src/models/user/userModel.js
Labels: bug, documentation, enhancement

#72 refactor job model queries to include is_shown filter and improve for…
  src/models/jobs/jobModel.js
Labels: enhancement

#95 PR: fix accepting pending applicnats
  ATS script.txt
  package-lock.json
  package.json
  public/index.html
  src/app.js
  src/config/gdrive.js
  src/controllers/analytic/dashboardController.js
  src/controllers/analytic/graphsController.js
  src/controllers/analytic/metricsController.js
  src/controllers/applicant/addApplicantController.js
  src/controllers/applicant/applicantController.js
  src/controllers/applicant/checkApplicantController.js
  src/controllers/applicant/editApplicantController.js
  src/controllers/applicant/pendingApplicantController.js
  src/controllers/applicant/statusHistoryController.js
  src/controllers/applicant/updateStatusController.js
  src/controllers/company/positionController.js
  src/controllers/counter/applicantCounterController.js
  src/controllers/cronjob/updateStatus.js
  src/controllers/email/emailController.js
  src/controllers/interview/interviewController.js
  src/controllers/jobs/industryController.js
  src/controllers/jobs/jobController.js
  src/controllers/jobs/setupController.js
  src/controllers/notification/notificationController.js
  src/controllers/password/passwordController.js
  src/controllers/upload/uploadController.js
  src/controllers/user/userController.js
  src/controllers/userConfiguration/gdriveConfigurationController.js
  src/controllers/userConfiguration/userConfigurationController.js
  src/index.js
  src/models/analytic/metricModel.js
  src/models/applicant/applicantModel.js
  src/models/interview/interviewModel.js
  src/models/jobs/industryModel.js
  src/models/jobs/jobModel.js
  src/models/jobs/setupModel.js
  src/models/position/positionModel.js
  src/models/user/userModel.js
  src/models/userConfiguration/gdriveModel.js
  src/models/userConfiguration/smtpModel.js
  src/routes/analytic/dashboardRoutes.js
  src/routes/analytic/graphsRoutes.js
  src/routes/analytic/metricsRoutes.js
  src/routes/applicant/applicantRoutes.js
  src/routes/applicant/checkApplicantRoutes.js
  src/routes/applicant/pendingApplicantRoutes.js
  src/routes/applicant/statHistoryRoutes.js
  src/routes/company/positionRoutes.js
  src/routes/email/emailRoutes.js
  src/routes/interview/interviewRoutes.js
  src/routes/jobs/industryRoutes.js
  src/routes/jobs/jobRoutes.js
  src/routes/jobs/setupRoutes.js
  src/routes/password/passwordRoutes.js
  src/routes/upload/uploadRoutes.js
  src/routes/user/userRoutes.js
  src/routes/userConfiguration/userConfigurationRoutes.js
  src/utils/date.js
  src/utils/statusMapping.js
Labels: bug

#109 fix: correct company_id assignment in uploadCVGdrive function
  src/controllers/upload/uploadController.js
Labels: bug
